[package]
name = "strides"
version = "1.0.0-rc.4"
edition = "2021"
rust-version = "1.85"
description = "Async-first terminal UI spinners and progress bars"
license = "MIT"
documentation = "https://docs.rs/strides"
repository = "https://github.com/matze/strides"

[workspace]
resolver = "3"

[dependencies]
futures-timer = "3.0.0"
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
futures-lite = "2.0"
owo-colors = "4.0.0"
pin-project-lite = "0.2"
terminal_size = "0.4"

[dev-dependencies]
async-io = "2.3.0"
async-signal = "0.2"
anyhow = "1.0.100"
clap = { version = "3.2.0", features = ["derive"] }
criterion = { version = "0.5", default-features = false }
futures = { version = "0.3.0", default-features = false, features = ["alloc"] }
futures-concurrency = "7.4.0"
reqwest = { version = "0.11.0", default-features = false, features = ["rustls", "stream"] }
tokio = { version = "1.47.0", features = ["full"] }
tokio-util = { version = "0.7.17", features = ["codec", "io"] }

[lints.rust]
unused_must_use = "forbid"
unsafe_code = "forbid"

[lints.clippy]
panic = "forbid"
todo = "forbid"
unimplemented = "forbid"
unwrap_used = "forbid"

[[bench]]
name = "render"
harness = false
